2663 Tri Tiling (1)
1163 The Triangle (1)
1160 Post Office (2)
2033 Alphacode (2)
1159 Palindrome (3)
1050 To the Max (4)
2127 Greatest Common Increasing Subsequence (6)
1655 Balancing Act (6)
2292 Optimal Keypad (6)
2430 Lazy Cows (7)
2066 Minimax Triangulation (8, challenge problem)
Hint: The edge between vertex 1 and m must be a part of some triangle.
Another hint: Use interval DP.
1038 Bugs Integrated, Inc. (9, challenge problem)
Hint: How can Problem 2663 help you?
